name:                bird
version:             0.1.0.0
github:              "Kohei-Wada/bird"
license:             BSD3
author:              "Kohei-Wada"
maintainer:          "program3152019@gmail.com"
copyright:           "2021 Kohei Wada"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Kohei-Wada/bird#readme>

dependencies:
- base >= 4.7 && < 5
- gloss >= 0.2.3
- gloss-juicy
- random


library:
  source-dirs: src

executables:
  bird-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bird

tests:
  bird-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bird



